/*
 * generated by Xtext 2.16.0
 */
package org.xtext.example.avante


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class PrescriptionRuntimeModule extends AbstractPrescriptionRuntimeModule {
}
