/*
 * generated by Xtext 2.16.0
 */
package org.xtext.example.avante


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class PrescriptionStandaloneSetup extends PrescriptionStandaloneSetupGenerated {

	def static void doSetup() {
		new PrescriptionStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
