/**
 * generated by Xtext 2.16.0
 */
package org.xtext.example.avante;

import org.xtext.example.avante.AbstractPrescriptionRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class PrescriptionRuntimeModule extends AbstractPrescriptionRuntimeModule {
}
