/**
 * generated by Xtext 2.16.0
 */
package org.xtext.example.avante;

import org.xtext.example.avante.PrescriptionStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class PrescriptionStandaloneSetup extends PrescriptionStandaloneSetupGenerated {
  public static void doSetup() {
    new PrescriptionStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
