/**
 * generated by Xtext 2.16.0
 */
package org.xtext.example.avante.validation;

import org.xtext.example.avante.validation.AbstractPrescriptionValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class PrescriptionValidator extends AbstractPrescriptionValidator {
}
