/*
 * generated by Xtext 2.16.0
 */
package org.xtext.example.avante.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class PrescriptionAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("org/xtext/example/avante/parser/antlr/internal/InternalPrescription.tokens");
	}
}
