/*
 * generated by Xtext 2.16.0
 */
package org.xtext.example.avante.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.xtext.example.avante.parser.antlr.internal.InternalPrescriptionParser;
import org.xtext.example.avante.services.PrescriptionGrammarAccess;

public class PrescriptionParser extends AbstractAntlrParser {

	@Inject
	private PrescriptionGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalPrescriptionParser createParser(XtextTokenStream stream) {
		return new InternalPrescriptionParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "DomainModel";
	}

	public PrescriptionGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(PrescriptionGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
