/**
 * generated by Xtext 2.16.0
 */
package org.xtext.example.avante.prescription;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Integer Params</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.avante.prescription.IntegerParams#getMeasureUnit <em>Measure Unit</em>}</li>
 *   <li>{@link org.xtext.example.avante.prescription.IntegerParams#getMinValue <em>Min Value</em>}</li>
 *   <li>{@link org.xtext.example.avante.prescription.IntegerParams#getMaxValue <em>Max Value</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.avante.prescription.PrescriptionPackage#getIntegerParams()
 * @model
 * @generated
 */
public interface IntegerParams extends EObject
{
  /**
   * Returns the value of the '<em><b>Measure Unit</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Measure Unit</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Measure Unit</em>' attribute.
   * @see #setMeasureUnit(String)
   * @see org.xtext.example.avante.prescription.PrescriptionPackage#getIntegerParams_MeasureUnit()
   * @model
   * @generated
   */
  String getMeasureUnit();

  /**
   * Sets the value of the '{@link org.xtext.example.avante.prescription.IntegerParams#getMeasureUnit <em>Measure Unit</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Measure Unit</em>' attribute.
   * @see #getMeasureUnit()
   * @generated
   */
  void setMeasureUnit(String value);

  /**
   * Returns the value of the '<em><b>Min Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Min Value</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Min Value</em>' attribute.
   * @see #setMinValue(int)
   * @see org.xtext.example.avante.prescription.PrescriptionPackage#getIntegerParams_MinValue()
   * @model
   * @generated
   */
  int getMinValue();

  /**
   * Sets the value of the '{@link org.xtext.example.avante.prescription.IntegerParams#getMinValue <em>Min Value</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Min Value</em>' attribute.
   * @see #getMinValue()
   * @generated
   */
  void setMinValue(int value);

  /**
   * Returns the value of the '<em><b>Max Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Max Value</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Max Value</em>' attribute.
   * @see #setMaxValue(int)
   * @see org.xtext.example.avante.prescription.PrescriptionPackage#getIntegerParams_MaxValue()
   * @model
   * @generated
   */
  int getMaxValue();

  /**
   * Sets the value of the '{@link org.xtext.example.avante.prescription.IntegerParams#getMaxValue <em>Max Value</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Max Value</em>' attribute.
   * @see #getMaxValue()
   * @generated
   */
  void setMaxValue(int value);

} // IntegerParams
