/**
 * generated by Xtext 2.16.0
 */
package org.xtext.example.avante.prescription;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.xtext.example.avante.prescription.PrescriptionFactory
 * @model kind="package"
 * @generated
 */
public interface PrescriptionPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "prescription";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.xtext.org/example/avante/Prescription";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "prescription";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  PrescriptionPackage eINSTANCE = org.xtext.example.avante.prescription.impl.PrescriptionPackageImpl.init();

  /**
   * The meta object id for the '{@link org.xtext.example.avante.prescription.impl.DomainModelImpl <em>Domain Model</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.avante.prescription.impl.DomainModelImpl
   * @see org.xtext.example.avante.prescription.impl.PrescriptionPackageImpl#getDomainModel()
   * @generated
   */
  int DOMAIN_MODEL = 0;

  /**
   * The feature id for the '<em><b>Elements</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DOMAIN_MODEL__ELEMENTS = 0;

  /**
   * The number of structural features of the '<em>Domain Model</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DOMAIN_MODEL_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.avante.prescription.impl.PrescriptionImpl <em>Prescription</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.avante.prescription.impl.PrescriptionImpl
   * @see org.xtext.example.avante.prescription.impl.PrescriptionPackageImpl#getPrescription()
   * @generated
   */
  int PRESCRIPTION = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PRESCRIPTION__NAME = 0;

  /**
   * The feature id for the '<em><b>Features</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PRESCRIPTION__FEATURES = 1;

  /**
   * The number of structural features of the '<em>Prescription</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PRESCRIPTION_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.example.avante.prescription.impl.AttributeImpl <em>Attribute</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.avante.prescription.impl.AttributeImpl
   * @see org.xtext.example.avante.prescription.impl.PrescriptionPackageImpl#getAttribute()
   * @generated
   */
  int ATTRIBUTE = 2;

  /**
   * The feature id for the '<em><b>Many</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATTRIBUTE__MANY = 0;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATTRIBUTE__NAME = 1;

  /**
   * The feature id for the '<em><b>Attr Params</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATTRIBUTE__ATTR_PARAMS = 2;

  /**
   * The number of structural features of the '<em>Attribute</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATTRIBUTE_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.xtext.example.avante.prescription.impl.AttributeParamsImpl <em>Attribute Params</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.avante.prescription.impl.AttributeParamsImpl
   * @see org.xtext.example.avante.prescription.impl.PrescriptionPackageImpl#getAttributeParams()
   * @generated
   */
  int ATTRIBUTE_PARAMS = 3;

  /**
   * The feature id for the '<em><b>Int Params</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATTRIBUTE_PARAMS__INT_PARAMS = 0;

  /**
   * The feature id for the '<em><b>Str Params</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATTRIBUTE_PARAMS__STR_PARAMS = 1;

  /**
   * The number of structural features of the '<em>Attribute Params</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATTRIBUTE_PARAMS_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.example.avante.prescription.impl.IntegerParamsImpl <em>Integer Params</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.avante.prescription.impl.IntegerParamsImpl
   * @see org.xtext.example.avante.prescription.impl.PrescriptionPackageImpl#getIntegerParams()
   * @generated
   */
  int INTEGER_PARAMS = 4;

  /**
   * The feature id for the '<em><b>Measure Unit</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INTEGER_PARAMS__MEASURE_UNIT = 0;

  /**
   * The feature id for the '<em><b>Min Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INTEGER_PARAMS__MIN_VALUE = 1;

  /**
   * The feature id for the '<em><b>Max Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INTEGER_PARAMS__MAX_VALUE = 2;

  /**
   * The number of structural features of the '<em>Integer Params</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INTEGER_PARAMS_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.xtext.example.avante.prescription.impl.StringParamsImpl <em>String Params</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.avante.prescription.impl.StringParamsImpl
   * @see org.xtext.example.avante.prescription.impl.PrescriptionPackageImpl#getStringParams()
   * @generated
   */
  int STRING_PARAMS = 5;

  /**
   * The feature id for the '<em><b>Def Value</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STRING_PARAMS__DEF_VALUE = 0;

  /**
   * The number of structural features of the '<em>String Params</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STRING_PARAMS_FEATURE_COUNT = 1;


  /**
   * Returns the meta object for class '{@link org.xtext.example.avante.prescription.DomainModel <em>Domain Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Domain Model</em>'.
   * @see org.xtext.example.avante.prescription.DomainModel
   * @generated
   */
  EClass getDomainModel();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.avante.prescription.DomainModel#getElements <em>Elements</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Elements</em>'.
   * @see org.xtext.example.avante.prescription.DomainModel#getElements()
   * @see #getDomainModel()
   * @generated
   */
  EReference getDomainModel_Elements();

  /**
   * Returns the meta object for class '{@link org.xtext.example.avante.prescription.Prescription <em>Prescription</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Prescription</em>'.
   * @see org.xtext.example.avante.prescription.Prescription
   * @generated
   */
  EClass getPrescription();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.avante.prescription.Prescription#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.avante.prescription.Prescription#getName()
   * @see #getPrescription()
   * @generated
   */
  EAttribute getPrescription_Name();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.avante.prescription.Prescription#getFeatures <em>Features</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Features</em>'.
   * @see org.xtext.example.avante.prescription.Prescription#getFeatures()
   * @see #getPrescription()
   * @generated
   */
  EReference getPrescription_Features();

  /**
   * Returns the meta object for class '{@link org.xtext.example.avante.prescription.Attribute <em>Attribute</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Attribute</em>'.
   * @see org.xtext.example.avante.prescription.Attribute
   * @generated
   */
  EClass getAttribute();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.avante.prescription.Attribute#isMany <em>Many</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Many</em>'.
   * @see org.xtext.example.avante.prescription.Attribute#isMany()
   * @see #getAttribute()
   * @generated
   */
  EAttribute getAttribute_Many();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.avante.prescription.Attribute#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.avante.prescription.Attribute#getName()
   * @see #getAttribute()
   * @generated
   */
  EAttribute getAttribute_Name();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.avante.prescription.Attribute#getAttrParams <em>Attr Params</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Attr Params</em>'.
   * @see org.xtext.example.avante.prescription.Attribute#getAttrParams()
   * @see #getAttribute()
   * @generated
   */
  EReference getAttribute_AttrParams();

  /**
   * Returns the meta object for class '{@link org.xtext.example.avante.prescription.AttributeParams <em>Attribute Params</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Attribute Params</em>'.
   * @see org.xtext.example.avante.prescription.AttributeParams
   * @generated
   */
  EClass getAttributeParams();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.avante.prescription.AttributeParams#getIntParams <em>Int Params</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Int Params</em>'.
   * @see org.xtext.example.avante.prescription.AttributeParams#getIntParams()
   * @see #getAttributeParams()
   * @generated
   */
  EReference getAttributeParams_IntParams();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.avante.prescription.AttributeParams#getStrParams <em>Str Params</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Str Params</em>'.
   * @see org.xtext.example.avante.prescription.AttributeParams#getStrParams()
   * @see #getAttributeParams()
   * @generated
   */
  EReference getAttributeParams_StrParams();

  /**
   * Returns the meta object for class '{@link org.xtext.example.avante.prescription.IntegerParams <em>Integer Params</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Integer Params</em>'.
   * @see org.xtext.example.avante.prescription.IntegerParams
   * @generated
   */
  EClass getIntegerParams();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.avante.prescription.IntegerParams#getMeasureUnit <em>Measure Unit</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Measure Unit</em>'.
   * @see org.xtext.example.avante.prescription.IntegerParams#getMeasureUnit()
   * @see #getIntegerParams()
   * @generated
   */
  EAttribute getIntegerParams_MeasureUnit();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.avante.prescription.IntegerParams#getMinValue <em>Min Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Min Value</em>'.
   * @see org.xtext.example.avante.prescription.IntegerParams#getMinValue()
   * @see #getIntegerParams()
   * @generated
   */
  EAttribute getIntegerParams_MinValue();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.avante.prescription.IntegerParams#getMaxValue <em>Max Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Max Value</em>'.
   * @see org.xtext.example.avante.prescription.IntegerParams#getMaxValue()
   * @see #getIntegerParams()
   * @generated
   */
  EAttribute getIntegerParams_MaxValue();

  /**
   * Returns the meta object for class '{@link org.xtext.example.avante.prescription.StringParams <em>String Params</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>String Params</em>'.
   * @see org.xtext.example.avante.prescription.StringParams
   * @generated
   */
  EClass getStringParams();

  /**
   * Returns the meta object for the attribute list '{@link org.xtext.example.avante.prescription.StringParams#getDefValue <em>Def Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Def Value</em>'.
   * @see org.xtext.example.avante.prescription.StringParams#getDefValue()
   * @see #getStringParams()
   * @generated
   */
  EAttribute getStringParams_DefValue();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  PrescriptionFactory getPrescriptionFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.xtext.example.avante.prescription.impl.DomainModelImpl <em>Domain Model</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.avante.prescription.impl.DomainModelImpl
     * @see org.xtext.example.avante.prescription.impl.PrescriptionPackageImpl#getDomainModel()
     * @generated
     */
    EClass DOMAIN_MODEL = eINSTANCE.getDomainModel();

    /**
     * The meta object literal for the '<em><b>Elements</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DOMAIN_MODEL__ELEMENTS = eINSTANCE.getDomainModel_Elements();

    /**
     * The meta object literal for the '{@link org.xtext.example.avante.prescription.impl.PrescriptionImpl <em>Prescription</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.avante.prescription.impl.PrescriptionImpl
     * @see org.xtext.example.avante.prescription.impl.PrescriptionPackageImpl#getPrescription()
     * @generated
     */
    EClass PRESCRIPTION = eINSTANCE.getPrescription();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PRESCRIPTION__NAME = eINSTANCE.getPrescription_Name();

    /**
     * The meta object literal for the '<em><b>Features</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PRESCRIPTION__FEATURES = eINSTANCE.getPrescription_Features();

    /**
     * The meta object literal for the '{@link org.xtext.example.avante.prescription.impl.AttributeImpl <em>Attribute</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.avante.prescription.impl.AttributeImpl
     * @see org.xtext.example.avante.prescription.impl.PrescriptionPackageImpl#getAttribute()
     * @generated
     */
    EClass ATTRIBUTE = eINSTANCE.getAttribute();

    /**
     * The meta object literal for the '<em><b>Many</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ATTRIBUTE__MANY = eINSTANCE.getAttribute_Many();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ATTRIBUTE__NAME = eINSTANCE.getAttribute_Name();

    /**
     * The meta object literal for the '<em><b>Attr Params</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ATTRIBUTE__ATTR_PARAMS = eINSTANCE.getAttribute_AttrParams();

    /**
     * The meta object literal for the '{@link org.xtext.example.avante.prescription.impl.AttributeParamsImpl <em>Attribute Params</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.avante.prescription.impl.AttributeParamsImpl
     * @see org.xtext.example.avante.prescription.impl.PrescriptionPackageImpl#getAttributeParams()
     * @generated
     */
    EClass ATTRIBUTE_PARAMS = eINSTANCE.getAttributeParams();

    /**
     * The meta object literal for the '<em><b>Int Params</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ATTRIBUTE_PARAMS__INT_PARAMS = eINSTANCE.getAttributeParams_IntParams();

    /**
     * The meta object literal for the '<em><b>Str Params</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ATTRIBUTE_PARAMS__STR_PARAMS = eINSTANCE.getAttributeParams_StrParams();

    /**
     * The meta object literal for the '{@link org.xtext.example.avante.prescription.impl.IntegerParamsImpl <em>Integer Params</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.avante.prescription.impl.IntegerParamsImpl
     * @see org.xtext.example.avante.prescription.impl.PrescriptionPackageImpl#getIntegerParams()
     * @generated
     */
    EClass INTEGER_PARAMS = eINSTANCE.getIntegerParams();

    /**
     * The meta object literal for the '<em><b>Measure Unit</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute INTEGER_PARAMS__MEASURE_UNIT = eINSTANCE.getIntegerParams_MeasureUnit();

    /**
     * The meta object literal for the '<em><b>Min Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute INTEGER_PARAMS__MIN_VALUE = eINSTANCE.getIntegerParams_MinValue();

    /**
     * The meta object literal for the '<em><b>Max Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute INTEGER_PARAMS__MAX_VALUE = eINSTANCE.getIntegerParams_MaxValue();

    /**
     * The meta object literal for the '{@link org.xtext.example.avante.prescription.impl.StringParamsImpl <em>String Params</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.avante.prescription.impl.StringParamsImpl
     * @see org.xtext.example.avante.prescription.impl.PrescriptionPackageImpl#getStringParams()
     * @generated
     */
    EClass STRING_PARAMS = eINSTANCE.getStringParams();

    /**
     * The meta object literal for the '<em><b>Def Value</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute STRING_PARAMS__DEF_VALUE = eINSTANCE.getStringParams_DefValue();

  }

} //PrescriptionPackage
