/**
 * generated by Xtext 2.16.0
 */
package org.xtext.example.avante.prescription;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>String Params</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.avante.prescription.StringParams#getDefValue <em>Def Value</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.avante.prescription.PrescriptionPackage#getStringParams()
 * @model
 * @generated
 */
public interface StringParams extends EObject
{
  /**
   * Returns the value of the '<em><b>Def Value</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Def Value</em>' attribute list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Def Value</em>' attribute list.
   * @see org.xtext.example.avante.prescription.PrescriptionPackage#getStringParams_DefValue()
   * @model unique="false"
   * @generated
   */
  EList<String> getDefValue();

} // StringParams
