/**
 * generated by Xtext 2.16.0
 */
package org.xtext.example.avante.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;
import org.xtext.example.avante.ui.AbstractPrescriptionUiModule;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class PrescriptionUiModule extends AbstractPrescriptionUiModule {
  public PrescriptionUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
