/*
 * generated by Xtext 2.16.0
 */
package org.xtext.example.avante.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractPrescriptionScopeProvider extends DelegatingScopeProvider {
}
