/**
 * generated by Xtext 2.16.0
 */
package org.xtext.example.avante.ide;

import org.xtext.example.avante.ide.AbstractPrescriptionIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class PrescriptionIdeModule extends AbstractPrescriptionIdeModule {
}
