/**
 * generated by Xtext 2.16.0
 */
package org.xtext.example.avante.prescription.impl;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.example.avante.prescription.Attribute;
import org.xtext.example.avante.prescription.AttributeParams;
import org.xtext.example.avante.prescription.PrescriptionPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Attribute</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.avante.prescription.impl.AttributeImpl#isMany <em>Many</em>}</li>
 *   <li>{@link org.xtext.example.avante.prescription.impl.AttributeImpl#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.example.avante.prescription.impl.AttributeImpl#getAttrParams <em>Attr Params</em>}</li>
 * </ul>
 *
 * @generated
 */
public class AttributeImpl extends MinimalEObjectImpl.Container implements Attribute
{
  /**
   * The default value of the '{@link #isMany() <em>Many</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isMany()
   * @generated
   * @ordered
   */
  protected static final boolean MANY_EDEFAULT = false;

  /**
   * The cached value of the '{@link #isMany() <em>Many</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isMany()
   * @generated
   * @ordered
   */
  protected boolean many = MANY_EDEFAULT;

  /**
   * The default value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected static final String NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected String name = NAME_EDEFAULT;

  /**
   * The cached value of the '{@link #getAttrParams() <em>Attr Params</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getAttrParams()
   * @generated
   * @ordered
   */
  protected AttributeParams attrParams;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected AttributeImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return PrescriptionPackage.Literals.ATTRIBUTE;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean isMany()
  {
    return many;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setMany(boolean newMany)
  {
    boolean oldMany = many;
    many = newMany;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, PrescriptionPackage.ATTRIBUTE__MANY, oldMany, many));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setName(String newName)
  {
    String oldName = name;
    name = newName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, PrescriptionPackage.ATTRIBUTE__NAME, oldName, name));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public AttributeParams getAttrParams()
  {
    return attrParams;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetAttrParams(AttributeParams newAttrParams, NotificationChain msgs)
  {
    AttributeParams oldAttrParams = attrParams;
    attrParams = newAttrParams;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, PrescriptionPackage.ATTRIBUTE__ATTR_PARAMS, oldAttrParams, newAttrParams);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setAttrParams(AttributeParams newAttrParams)
  {
    if (newAttrParams != attrParams)
    {
      NotificationChain msgs = null;
      if (attrParams != null)
        msgs = ((InternalEObject)attrParams).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - PrescriptionPackage.ATTRIBUTE__ATTR_PARAMS, null, msgs);
      if (newAttrParams != null)
        msgs = ((InternalEObject)newAttrParams).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - PrescriptionPackage.ATTRIBUTE__ATTR_PARAMS, null, msgs);
      msgs = basicSetAttrParams(newAttrParams, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, PrescriptionPackage.ATTRIBUTE__ATTR_PARAMS, newAttrParams, newAttrParams));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case PrescriptionPackage.ATTRIBUTE__ATTR_PARAMS:
        return basicSetAttrParams(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case PrescriptionPackage.ATTRIBUTE__MANY:
        return isMany();
      case PrescriptionPackage.ATTRIBUTE__NAME:
        return getName();
      case PrescriptionPackage.ATTRIBUTE__ATTR_PARAMS:
        return getAttrParams();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case PrescriptionPackage.ATTRIBUTE__MANY:
        setMany((Boolean)newValue);
        return;
      case PrescriptionPackage.ATTRIBUTE__NAME:
        setName((String)newValue);
        return;
      case PrescriptionPackage.ATTRIBUTE__ATTR_PARAMS:
        setAttrParams((AttributeParams)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case PrescriptionPackage.ATTRIBUTE__MANY:
        setMany(MANY_EDEFAULT);
        return;
      case PrescriptionPackage.ATTRIBUTE__NAME:
        setName(NAME_EDEFAULT);
        return;
      case PrescriptionPackage.ATTRIBUTE__ATTR_PARAMS:
        setAttrParams((AttributeParams)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case PrescriptionPackage.ATTRIBUTE__MANY:
        return many != MANY_EDEFAULT;
      case PrescriptionPackage.ATTRIBUTE__NAME:
        return NAME_EDEFAULT == null ? name != null : !NAME_EDEFAULT.equals(name);
      case PrescriptionPackage.ATTRIBUTE__ATTR_PARAMS:
        return attrParams != null;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (many: ");
    result.append(many);
    result.append(", name: ");
    result.append(name);
    result.append(')');
    return result.toString();
  }

} //AttributeImpl
