/**
 * generated by Xtext 2.16.0
 */
package org.xtext.example.avante.prescription.impl;

import java.util.Collection;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EDataTypeEList;

import org.xtext.example.avante.prescription.PrescriptionPackage;
import org.xtext.example.avante.prescription.StringParams;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>String Params</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.avante.prescription.impl.StringParamsImpl#getDefValue <em>Def Value</em>}</li>
 * </ul>
 *
 * @generated
 */
public class StringParamsImpl extends MinimalEObjectImpl.Container implements StringParams
{
  /**
   * The cached value of the '{@link #getDefValue() <em>Def Value</em>}' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDefValue()
   * @generated
   * @ordered
   */
  protected EList<String> defValue;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected StringParamsImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return PrescriptionPackage.Literals.STRING_PARAMS;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<String> getDefValue()
  {
    if (defValue == null)
    {
      defValue = new EDataTypeEList<String>(String.class, this, PrescriptionPackage.STRING_PARAMS__DEF_VALUE);
    }
    return defValue;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case PrescriptionPackage.STRING_PARAMS__DEF_VALUE:
        return getDefValue();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case PrescriptionPackage.STRING_PARAMS__DEF_VALUE:
        getDefValue().clear();
        getDefValue().addAll((Collection<? extends String>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case PrescriptionPackage.STRING_PARAMS__DEF_VALUE:
        getDefValue().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case PrescriptionPackage.STRING_PARAMS__DEF_VALUE:
        return defValue != null && !defValue.isEmpty();
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (defValue: ");
    result.append(defValue);
    result.append(')');
    return result.toString();
  }

} //StringParamsImpl
