/*
 * generated by Xtext 2.16.0
 */
package org.xtext.example.avante.ui;

import com.google.inject.Injector;
import org.eclipse.core.runtime.Platform;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.xtext.example.avante.ui.internal.AvanteActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class PrescriptionExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return Platform.getBundle(AvanteActivator.PLUGIN_ID);
	}
	
	@Override
	protected Injector getInjector() {
		AvanteActivator activator = AvanteActivator.getInstance();
		return activator != null ? activator.getInjector(AvanteActivator.ORG_XTEXT_EXAMPLE_AVANTE_PRESCRIPTION) : null;
	}

}
