/*
 * generated by Xtext 2.16.0
 */
package org.xtext.example.avante.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import org.xtext.example.avante.ui.internal.AvanteActivator;

public class PrescriptionUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return AvanteActivator.getInstance().getInjector("org.xtext.example.avante.Prescription");
	}

}
